field: 4dac4fc4-3765-438a-aa11-7a945ddd9c1e # Riders
fieldLayouts:
  4208adce-7e00-460e-a0c3-afac4c932a23:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: b2a42c2d-5550-4f63-981e-8a87c0191600 # Photo
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c0beb5c6-2e29-4b0b-a110-bc34fd88aca1
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 06986050-d90f-4539-a9aa-857c78baf772 # Full Name
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: bf31f48d-206c-4a02-a317-e00f08bb9f8c
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: bc0d93a9-955b-4ba2-abd1-478cb6e5fc45 # Description
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 979d2cc7-dba1-4422-931d-e0060e9015e2
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: ee86f819-26fb-4df5-be69-7208cd63a0d5
        userCondition: null
fields:
  06986050-d90f-4539-a9aa-857c78baf772: # Full Name
    columnSuffix: skrnqmvf
    contentColumnType: text
    fieldGroup: null
    handle: fullName
    instructions: null
    name: 'Full Name'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  b2a42c2d-5550-4f63-981e-8a87c0191600: # Photo
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: photo
    instructions: null
    name: Photo
    searchable: false
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds:
        - image
      branchLimit: null
      defaultUploadLocationSource: 'volume:3bbb2de8-f0b4-4127-aceb-9e8f03cd70fe' # Uploads
      defaultUploadLocationSubpath: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: 1
      minRelations: 1
      previewMode: full
      restrictFiles: true
      restrictLocation: false
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:3bbb2de8-f0b4-4127-aceb-9e8f03cd70fe' # Uploads
      restrictedLocationSubpath: null
      selectionLabel: 'Add a photo'
      showSiteMenu: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      sources:
        - 'volume:3bbb2de8-f0b4-4127-aceb-9e8f03cd70fe' # Uploads
      targetSiteId: null
      validateRelatedElements: false
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  bc0d93a9-955b-4ba2-abd1-478cb6e5fc45: # Description
    columnSuffix: ydphqzfc
    contentColumnType: text
    fieldGroup: null
    handle: description
    instructions: null
    name: Description
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 2
      multiline: true
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: rider
name: Rider
sortOrder: 1
