fieldLayouts:
  e6075d34-73a6-4b05-9710-b8b648e8cd99:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 30420768-ea7b-4e68-ba45-bdfd2f095698
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 1adba373-a6e0-4d86-8c84-35ff4bef8331 # Photos
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 90edd38c-c516-428b-af0f-c2fb066ebc70
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: c4aac1d2-5b3a-4474-8477-128505ad5998 # Excerpt
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b42bd761-e56f-4b5e-b504-5996577fbf8f
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 3b6fcc56-ab7c-4d22-89fb-29edcb6d9a17 # Rich Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 34c12a00-b4b9-4947-a1bd-65851acc4281
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 1af76a0d-9ca3-415e-b949-cc2493744e7c
        userCondition: null
handle: default
hasTitleField: true
name: Default
section: 210547a8-61b6-4642-8986-022e7e15c3e9 # Stories
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
