fieldLayouts:
  77c8118d-130a-438b-8ab8-4042cde58dff:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 87e3e736-1147-4650-a6e6-50448fb949be
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 0f4c8eec-6897-4c64-a85e-b46be8142a41
        userCondition: null
handle: storiesListing
hasTitleField: true
name: 'Stories Listing'
section: 6374f099-cd17-4faa-9b0d-4590cb98bcee # Stories Listing
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
