columnSuffix: null
contentColumnType: string
fieldGroup: 112351b0-7ce3-4c9b-b395-25dc7ec11f14 # Home Page
handle: featuredStory
instructions: null
name: 'Featured Story'
searchable: false
settings:
  allowSelfRelations: false
  branchLimit: null
  localizeRelations: false
  maintainHierarchy: false
  maxRelations: 1
  minRelations: 1
  selectionLabel: 'Select a story'
  showSiteMenu: false
  sources:
    - 'section:210547a8-61b6-4642-8986-022e7e15c3e9' # Stories
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Entries
