columnSuffix: rjdfhlif
contentColumnType: text
fieldGroup: 112351b0-7ce3-4c9b-b395-25dc7ec11f14 # Home Page
handle: heroTitle
instructions: null
name: 'Hero Title'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
