columnSuffix: null
contentColumnType: string
fieldGroup: 112351b0-7ce3-4c9b-b395-25dc7ec11f14 # Home Page
handle: heroImage
instructions: null
name: 'Hero Image'
searchable: false
settings:
  allowSelfRelations: false
  allowSubfolders: false
  allowUploads: true
  allowedKinds:
    - image
  branchLimit: null
  defaultUploadLocationSource: 'volume:3bbb2de8-f0b4-4127-aceb-9e8f03cd70fe' # Uploads
  defaultUploadLocationSubpath: null
  localizeRelations: false
  maintainHierarchy: false
  maxRelations: 1
  minRelations: 1
  previewMode: full
  restrictFiles: true
  restrictLocation: false
  restrictedDefaultUploadSubpath: null
  restrictedLocationSource: 'volume:3bbb2de8-f0b4-4127-aceb-9e8f03cd70fe' # Uploads
  restrictedLocationSubpath: null
  selectionLabel: 'Add a backgroud image'
  showSiteMenu: false
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  sources:
    - 'volume:3bbb2de8-f0b4-4127-aceb-9e8f03cd70fe' # Uploads
  targetSiteId: null
  validateRelatedElements: false
  viewMode: large
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
