columnSuffix: null
contentColumnType: string
fieldGroup: bd158d53-0918-4faf-b9a8-5567d986e9b8 # Common
handle: photos
instructions: null
name: Photos
searchable: false
settings:
  allowSelfRelations: false
  allowSubfolders: false
  allowUploads: true
  allowedKinds:
    - image
  branchLimit: null
  defaultUploadLocationSource: 'volume:3bbb2de8-f0b4-4127-aceb-9e8f03cd70fe' # Uploads
  defaultUploadLocationSubpath: null
  localizeRelations: false
  maintainHierarchy: false
  maxRelations: null
  minRelations: 1
  previewMode: full
  restrictFiles: true
  restrictLocation: false
  restrictedDefaultUploadSubpath: null
  restrictedLocationSource: 'volume:3bbb2de8-f0b4-4127-aceb-9e8f03cd70fe' # Uploads
  restrictedLocationSubpath: null
  selectionLabel: null
  showSiteMenu: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  sources:
    - 'volume:3bbb2de8-f0b4-4127-aceb-9e8f03cd70fe' # Uploads
  targetSiteId: null
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
