defaultPlacement: end
enableVersioning: true
handle: storiesListing
name: 'Stories Listing'
propagationMethod: all
siteSettings:
  a1bb40cf-139e-4d42-98bd-70eee02b46b9: # Motoventure
    enabledByDefault: true
    hasUrls: true
    template: stories/index.twig
    uriFormat: stories
type: single
